include:
  - project: 'implicity-healthcare/devops/gitlab-templates'
    ref: master
    file: 'templates/projects/angular.yml'

variables:
  NODE_VERSION: "22.15.0"
  IMAGE_NAME: "mpcty-admin-portal"
  TYPESCRIPT_VERSION: 5.6.2
  RUNNER_TAG: "fargate"
  MULTI_LANG_BUILD: "true"
