include:
  - project: 'implicity-healthcare/devops/gitlab-templates'
    ref: master
    file: 'templates/projects/nestjs.yml'

variables:
  NODE_VERSION: 20.12.2 # Exact node version
  TYPESCRIPT_VERSION: 5.0.4
  IMAGE_NAME: "wildcard-service" # Name of the container
  SERVICE_NAME: "wildcard-service" # Name of the service to be deployed (by operator)
  DEPLOYMENT_MODE: "auto" # Mode of CD for staging env
  LINT_REQUIRED: "true" # Make the lint step of the pipeline blocking
